apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orbital-sync
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lucasquin/orbital-sync.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: orbital-sync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
